### ISSUE TITLE
JWKS: add key distribution support

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-certmanager#11]
Parameters:
key_rotation_interval = 2h
jwks_sync_time = 60*20 + 10 #20 minutes plus small epsilon to allow for jitter

1) Create initial keys with expiration = key_rotation_interval + token_lifetime
2) Wait for key_rotation_interval - jwks_sync_time
3) create kid2 with expiration = key_rotation_interval + token_lifetime + jwks_sync_time # the extra time is needed as the key is created early
4) publish new jwks which contains original kid1 and new kid2
5) wait jwks_sync_time
6) push private jks to pods so they can use them
7) when kid1 expires remove it from jwks

**Comment by iromli** [comment]
Related issue: https://github.com/GluuFederation/oxAuth/issues/1470

**Comment by iromli** [comment]
The implementation required in 4.2.2 and above

**Comment by moabu** [comment]
### Implementation in https://github.com/GluuFederation/docker-certmanager/commit/dd63dfcbb77df7183884bb60b9fe4108fd62498b

Parameters:

- interval = 2 hours
- token lifetime = 1 hour
- jwks sync time = 20 minutes + 10 seconds
- cronjob interval = interval - jwks sync time = 1 hour 39 minutes 50 seconds

Steps:

1.  config-init generates initial keys at 01:00:00

    * expiration: interval + token lifetime = 3 hours
    * JWKS-1 and JKS-1 created, expired at 04:00:00

2.  first cronjob runs at 02:39:50

    * expiration: interval + token lifetime = 3 hours
    * JWKS-2 and JKS-2 created, expired at 05:39:50
    * JWKS-1 and JKS-1 not expired (04:00:00 is not surpassed); merged to JWKS-2 and JKS-2

3.  next cronjob runs at 04:19:40

    * expiration: interval + token lifetime = 3 hours
    * JWKS-3 and JKS-3 created, expired at 07:19:40
    * JWKS-1 and JKS-1 expired (04:00:00 is surpassed); removed from JWKS-2 and JKS-2
    * JWKS-2 and JKS-2 not expired (05:39:50 is not surpassed); merged to JWKS-3 and JKS-3

4.  next cronjob runs at 05:59:30

    * expiration = interval + token lifetime = 3 hours
    * JWKS-4 and JKS-4 created, expired at 08:59:30
    * JWKS-2 and JKS-2 expired (05:39:50 is surpassed); removed from JWKS-3 and JKS-3
    * JWKS-3 and JKS-3 not expired (07:19:40 is not surpassed); merged to JWKS-4 and JKS-4

5.  next cronjob runs at 07:39:20

    * expiration = interval + token lifetime = 3 hours
    * JWKS-5 and JKS-5 created, expired at 10:39:20
    * JWKS-3 and JKS-3 expired (07:19:40 is surpassed); removed from JWKS-4 and JKS-4
    * JWKS-4 and JKS-4 not expired (08:59:30 is not surpassed); merged to JWKS-5 and JKS-5

6   ... and so on


Note:

- jwks sync time is used only in calculating cronjob interval
- seems safer from race condition and time mismatch

**Comment by moabu** [comment]
Add a method `prune-expired-jks` to allow to run a separate `CronJob` to check and delete expired keys. This will prevent the possibility of holding an expired JKS key in store before the next new key is generated and hence the next expired key is checked.

**Comment by moabu** [comment]
Issue has been resolved.
